"""Regenerate reviewer-facing result tables.

This script is intentionally dependency-free. By default it reads the
reviewer-facing recomputable aggregate CSV and prints a compact ranked table
for the clean canonical paper row set: reconciled full-800 tool-use rows,
excluding attempted-only context-window-overflow rows. Use
``--row-set recomputable`` to include every reconciled aggregate row, including
attempted-only rows and direct-generation rows.

For paper-relevant checks, ``--table row-filter`` lists each aggregate row's
status, and ``--table per-class --row-set paper-main`` recomputes a
Table-2-style per-class summary from redacted per-scenario validation fields.
The redacted artifact does not include response-level refusal-audit judge
labels, so SR-infeasible values emitted here are detector provenance rather
than recovered audit labels.

``--table error-types`` summarizes the redacted ``error_message_type`` field
into coarse provider/runtime categories. It is not a validated failure-mode
taxonomy: rows without an exception can still be constraint failures,
calibration-behavior failures, malformed-but-parseable tool plans, or task
misunderstandings that require raw traces to separate.

The auditable ``supplementary/results/run_manifest.csv`` is generated by
``generate_review_artifacts.py`` from matched raw run summaries. For debugging
legacy aggregate rows, pass ``--write-preview-manifest <path>`` to write an
expected-path preview manifest without replacing the reviewed manifest.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


SUPPLEMENTARY_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RESULTS = SUPPLEMENTARY_ROOT / "results" / "main_results_recomputable.csv"
DEFAULT_MANIFEST = SUPPLEMENTARY_ROOT / "results" / "run_manifest.csv"
DEFAULT_PER_SCENARIO = SUPPLEMENTARY_ROOT / "results" / "per_scenario_results_redacted.csv"

ATTEMPTED_ONLY_ROW_IDS = {
    "56": "context-window overflow: Falcon3-1B",
    "57": "context-window overflow: Yi-1.5-34B",
    "58": "context-window overflow: OLMo-2-13B",
}

PAPER_MAIN_ROW_IDS = [
    "4",   # Gemini 3 Flash preview
    "1",   # QwQ-32B
    "2",   # Sonnet 4.6 thinking=8192
    "6",   # Qwen3-4B
    "3",   # Qwen3-32B
    "5",   # Qwen3-8B
    "9",   # Qwen2.5-32B
    "7",   # Qwen3.5-27B
    "10",  # DS-R1-32B
    "17",  # gpt-5.4-mini
    "19",  # GPT-5.4
    "18",  # Gemma 4 31B
    "20",  # Gemini 2.5 Flash
    "29",  # gpt-oss-120b
    "28",  # OLMo3-7B
]

AUDITED_REFUSAL_ROW_IDS = {"1", "3", "5", "6", "7", "9", "10", "28"}

DISPLAY_NAMES = {
    "1": "QwQ-32B",
    "2": "Sonnet 4.6 (thinking=8192)",
    "3": "Qwen3-32B",
    "4": "Gemini 3 Flash preview",
    "5": "Qwen3-8B",
    "6": "Qwen3-4B",
    "7": "Qwen3.5-27B",
    "9": "Qwen2.5-32B",
    "10": "DS-R1-32B",
    "17": "gpt-5.4-mini (medium, Resp. API)",
    "18": "Gemma 4 31B",
    "19": "GPT-5.4 (medium, Resp. API)",
    "20": "Gemini 2.5 Flash",
    "28": "OLMo3-7B",
    "29": "gpt-oss-120b",
}

TEXT_FALLBACK_MARKERS = (
    "Falcon3-",
    "Llama-3.1-8B",
    "Llama-3.2-",
    "Mistral-",
)


def _slug_model(model: str) -> str:
    return model.replace("/", "_").replace(":", "_")


def _summary_path(row: dict[str, str]) -> str:
    timestamp = row["timestamp"].split(".")[0].replace("T", "_").replace(":", "-")
    return f"results/{timestamp}_{_slug_model(row['model'])}/summary.json"


def _artifact_ref(path: Path) -> str:
    resolved = path.resolve()
    try:
        return resolved.relative_to(SUPPLEMENTARY_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _row_key(row: dict[str, str]) -> tuple[str, str, str, str]:
    return (row["model"], row["provider"], row["track"], row["timestamp"])


def _with_manifest_fields(
    rows: list[dict[str, str]],
    manifest_rows: list[dict[str, str]],
) -> list[dict[str, str]]:
    manifest_by_key = {_row_key(row): row for row in manifest_rows}
    out = []
    for row in rows:
        merged = dict(row)
        manifest = manifest_by_key.get(_row_key(row))
        if manifest:
            for field in (
                "row_id",
                "recompute_status",
                "excluded_from_recompute",
                "exclusion_reason",
                "redacted_rows_written",
            ):
                merged[field] = manifest.get(field, "")
        else:
            merged.setdefault("row_id", "")
            merged.setdefault("recompute_status", "unknown")
            merged.setdefault("excluded_from_recompute", "")
            merged.setdefault("exclusion_reason", "row not found in run_manifest.csv")
            merged.setdefault("redacted_rows_written", "")
        out.append(merged)
    return out


def _paper_status(row: dict[str, str]) -> str:
    row_id = row.get("row_id", "")
    if row.get("recompute_status") != "reconciled" or row.get("excluded_from_recompute") == "yes":
        return "provenance-only-nonrecomputable"
    if row_id in ATTEMPTED_ONLY_ROW_IDS:
        return "attempted-only-context-window-overflow"
    if row.get("track") == "open":
        return "paper-open-track"
    if row_id in PAPER_MAIN_ROW_IDS:
        return "paper-main-representative"
    if row.get("track") == "canonical":
        return "paper-clean-tool-use"
    return "recomputable-other"


def _matches_row_set(row: dict[str, str], row_set: str) -> bool:
    status = _paper_status(row)
    if row_set == "all":
        return True
    if row_set == "recomputable":
        return row.get("recompute_status") == "reconciled" and row.get("excluded_from_recompute") != "yes"
    if row_set == "paper-clean-tool":
        return status in {"paper-main-representative", "paper-clean-tool-use"}
    if row_set == "paper-clean-all":
        return status in {"paper-main-representative", "paper-clean-tool-use", "paper-open-track"}
    if row_set == "paper-main":
        return row.get("row_id", "") in PAPER_MAIN_ROW_IDS
    if row_set == "paper-open-track":
        return status == "paper-open-track"
    if row_set == "attempted-only":
        return status == "attempted-only-context-window-overflow"
    if row_set == "provenance-only":
        return status == "provenance-only-nonrecomputable"
    raise ValueError(f"unknown row set: {row_set}")


def _row_sort_key(row: dict[str, str]) -> tuple[int, str]:
    row_id = row.get("row_id", "")
    return (int(row_id) if row_id.isdigit() else 10_000, row.get("model", ""))


def _display_name(row: dict[str, str]) -> str:
    return DISPLAY_NAMES.get(row.get("row_id", ""), row["model"])


def _is_text_fallback(row: dict[str, str]) -> bool:
    model = row.get("model", "")
    return any(marker in model for marker in TEXT_FALLBACK_MARKERS)


def _bool(value: str) -> bool:
    return value.lower() == "true"


def _pct(numerator: int, denominator: int) -> float:
    return 100.0 * numerator / denominator if denominator else 0.0


def _band(value: float) -> str:
    if value < 30.0:
        return "low"
    if value < 60.0:
        return "mid"
    return "high"


def _error_message_category(message: str) -> str:
    msg = (message or "").lower()
    if not msg:
        return "no_error_message"
    if "maximum context length" in msg:
        return "provider_context_window_error"
    if "rate_limit" in msg or "rate limit" in msg or "429" in msg:
        return "provider_rate_limit_error"
    if "did not return final_state" in msg:
        return "missing_final_state"
    if "timeout" in msg:
        return "timeout_error"
    if "validation" in msg or "schema" in msg or "json" in msg:
        return "parse_or_validation_error"
    return "other_error_message"


def write_manifest(rows: list[dict[str, str]], out_path: Path, aggregate_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "row_id",
        "model",
        "provider",
        "track",
        "timestamp",
        "total_runs",
        "successful_runs",
        "sr",
        "aggregate_csv",
        "expected_summary_json",
        "per_call_logs_included",
        "notes",
    ]
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for idx, row in enumerate(rows, start=1):
            writer.writerow({
                "row_id": idx,
                "model": row["model"],
                "provider": row["provider"],
                "track": row["track"],
                "timestamp": row["timestamp"],
                "total_runs": row["total_runs"],
                "successful_runs": row["successful_runs"],
                "sr": row["sr"],
                "aggregate_csv": _artifact_ref(aggregate_path),
                "expected_summary_json": _summary_path(row),
                "per_call_logs_included": "no",
                "notes": (
                    "Aggregate row included in review bundle; summary/log "
                    "directory name follows harness output convention. "
                    "Per-call logs deferred for prompt-fingerprint and size reasons."
                ),
            })


def print_ranked_table(rows: list[dict[str, str]], limit: int, row_set: str) -> None:
    ranked = sorted(rows, key=lambda r: float(r["sr"]), reverse=True)
    shown = ranked if limit <= 0 else ranked[:limit]
    print(f"Row set: `{row_set}` ({len(rows)} rows). Aggregate SR is diagnostic and is not a paper leaderboard.")
    print()
    print("| Rank | Row | Model | Provider | Track | Runs | SR (%) | Paper status |")
    print("|---:|---:|---|---|---|---:|---:|---|")
    for rank, row in enumerate(shown, start=1):
        sr_pct = float(row["sr"]) * 100
        print(
            f"| {rank} | {row.get('row_id', '')} | {_display_name(row)} | "
            f"{row['provider']} | {row['track']} | {row['total_runs']} | "
            f"{sr_pct:.1f} | {_paper_status(row)} |"
        )


def print_row_filter(rows: list[dict[str, str]]) -> None:
    print("| Row | Model | Provider | Track | Runs | Recompute status | Paper/artifact status | Notes |")
    print("|---:|---|---|---|---:|---|---|---|")
    for row in sorted(rows, key=_row_sort_key):
        note = ""
        row_id = row.get("row_id", "")
        if row_id in ATTEMPTED_ONLY_ROW_IDS:
            note = ATTEMPTED_ONLY_ROW_IDS[row_id]
        elif _is_text_fallback(row):
            note = "text-fallback interface subgroup"
        elif row.get("exclusion_reason"):
            note = row["exclusion_reason"]
        print(
            f"| {row_id} | {_display_name(row)} | {row['provider']} | {row['track']} | "
            f"{row['total_runs']} | {row.get('recompute_status', '')} | "
            f"{_paper_status(row)} | {note} |"
        )


def _per_class_summaries(
    rows: list[dict[str, str]],
    per_scenario_path: Path,
) -> list[dict[str, str]]:
    row_ids = {row.get("row_id", "") for row in rows}
    records_by_row: dict[str, list[dict[str, str]]] = defaultdict(list)
    with per_scenario_path.open(newline="", encoding="utf-8") as f:
        for record in csv.DictReader(f):
            if record["row_id"] in row_ids:
                records_by_row[record["row_id"]].append(record)

    summaries = []
    rows_by_id = {row.get("row_id", ""): row for row in rows}
    for row_id, records in records_by_row.items():
        row = rows_by_id[row_id]
        by_feasibility: dict[str, list[dict[str, str]]] = defaultdict(list)
        for record in records:
            by_feasibility[record["scenario_feasibility"]].append(record)

        feasible = by_feasibility["feasible"]
        infeasible = by_feasibility["infeasible"]
        ambiguous = by_feasibility["ambiguous"]
        sr_feas = _pct(sum(_bool(r["success"]) for r in feasible), len(feasible))
        sr_inf_detector = _pct(sum(_bool(r["success"]) for r in infeasible), len(infeasible))
        sr_amb_loose = _pct(sum(_bool(r["success"]) for r in ambiguous), len(ambiguous))
        sr_amb_strict = _pct(
            sum(r["behavior"] == "clarify" and not _bool(r["state_changed"]) for r in ambiguous),
            len(ambiguous),
        )

        note_parts = []
        if row_id in AUDITED_REFUSAL_ROW_IDS:
            note_parts.append("paper SR-inf uses aggregate audit; detector shown here")
        if _is_text_fallback(row):
            note_parts.append("text fallback")
        summaries.append({
            "row_id": row_id,
            "system": _display_name(row),
            "provider": row["provider"],
            "track": row["track"],
            "runs": str(len(records)),
            "sr": f"{float(row['sr']) * 100:.1f}",
            "sr_feas": f"{sr_feas:.1f}",
            "sr_inf_detector": f"{sr_inf_detector:.1f}",
            "sr_inf_detector_band": _band(sr_inf_detector),
            "sr_amb_loose": f"{sr_amb_loose:.1f}",
            "sr_amb_strict": f"{sr_amb_strict:.1f}",
            "sr_amb_strict_band": _band(sr_amb_strict),
            "note": "; ".join(note_parts),
        })
    return summaries


def _per_class_sort_key(summary: dict[str, str], row_set: str) -> tuple[int | float, str]:
    if row_set == "paper-main":
        return (PAPER_MAIN_ROW_IDS.index(summary["row_id"]), "")
    return (-float(summary["sr_feas"]), summary["system"])


def print_per_class_table(
    rows: list[dict[str, str]],
    per_scenario_path: Path,
    limit: int,
    row_set: str,
) -> None:
    summaries = _per_class_summaries(rows, per_scenario_path)
    summaries = sorted(summaries, key=lambda s: _per_class_sort_key(s, row_set))
    if limit > 0:
        summaries = summaries[:limit]

    print(f"Row set: `{row_set}` ({len(rows)} aggregate rows). Values are recomputed from redacted per-scenario fields.")
    print("SR-inf is detector provenance; response-level refusal-audit labels are not in the anonymous bundle.")
    print()
    print(
        "| Row | System | Runs | SR-feas (%) | SR-inf det. (%) | "
        "SR-inf det. band | SR-amb strict (%) | SR-amb strict band | Note |"
    )
    print("|---:|---|---:|---:|---:|---|---:|---|---|")
    for summary in summaries:
        print(
            f"| {summary['row_id']} | {summary['system']} | {summary['runs']} | "
            f"{summary['sr_feas']} | {summary['sr_inf_detector']} | "
            f"{summary['sr_inf_detector_band']} | {summary['sr_amb_strict']} | "
            f"{summary['sr_amb_strict_band']} | {summary['note']} |"
        )


def print_error_type_table(
    rows: list[dict[str, str]],
    per_scenario_path: Path,
    row_set: str,
) -> None:
    row_ids = {row.get("row_id", "") for row in rows}
    counts: dict[str, dict[str, int]] = defaultdict(lambda: {"total": 0, "success": 0, "failure": 0})
    total = 0
    with per_scenario_path.open(newline="", encoding="utf-8") as f:
        for record in csv.DictReader(f):
            if record["row_id"] not in row_ids:
                continue
            total += 1
            category = _error_message_category(record.get("error_message_type", ""))
            counts[category]["total"] += 1
            if _bool(record.get("success", "")):
                counts[category]["success"] += 1
            else:
                counts[category]["failure"] += 1

    print(f"Row set: `{row_set}` ({len(rows)} aggregate rows; {total} redacted scenario-run records).")
    print("Categories are derived from redacted `error_message_type`; this is not a validated task-failure taxonomy.")
    print()
    print("| Category | Records | Share (%) | Successes | Failures |")
    print("|---|---:|---:|---:|---:|")
    for category, vals in sorted(counts.items(), key=lambda item: (-item[1]["total"], item[0])):
        share = _pct(vals["total"], total)
        print(
            f"| {category} | {vals['total']} | {share:.2f} | "
            f"{vals['success']} | {vals['failure']} |"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    parser.add_argument(
        "--run-manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="Input run manifest generated during artifact preparation.",
    )
    parser.add_argument("--per-scenario", type=Path, default=DEFAULT_PER_SCENARIO)
    parser.add_argument(
        "--table",
        choices=["aggregate", "row-filter", "per-class", "error-types"],
        default="aggregate",
        help="Table to print.",
    )
    parser.add_argument(
        "--row-set",
        choices=[
            "all",
            "recomputable",
            "paper-clean-tool",
            "paper-clean-all",
            "paper-main",
            "paper-open-track",
            "attempted-only",
            "provenance-only",
        ],
        default=None,
        help=(
            "Rows to include. Defaults to paper-clean-tool for aggregate/per-class "
            "and all rows for row-filter."
        ),
    )
    parser.add_argument(
        "--write-preview-manifest",
        type=Path,
        default=None,
        help="Optional output path for a legacy expected-summary preview manifest.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help=(
            "Deprecated alias for --write-preview-manifest, retained for older "
            "review instructions."
        ),
    )
    parser.add_argument("--limit", type=int, default=20)
    args = parser.parse_args()

    manifest_rows = load_rows(args.run_manifest)
    if args.table == "row-filter":
        row_set = args.row_set or "all"
        rows = manifest_rows
    else:
        row_set = args.row_set or "paper-clean-tool"
        rows = _with_manifest_fields(load_rows(args.results), manifest_rows)

    rows = [row for row in rows if _matches_row_set(row, row_set)]

    if args.table == "aggregate":
        print_ranked_table(rows, args.limit, row_set)
    elif args.table == "row-filter":
        print_row_filter(rows)
    elif args.table == "per-class":
        print_per_class_table(rows, args.per_scenario, args.limit, row_set)
    elif args.table == "error-types":
        print_error_type_table(rows, args.per_scenario, row_set)

    preview_manifest = args.write_preview_manifest or args.manifest
    if preview_manifest is not None:
        write_manifest(rows, preview_manifest, args.results)
        print(f"\nWrote legacy expected-path manifest: {preview_manifest}")


if __name__ == "__main__":
    main()
